apiVersion: v1
kind: Template
labels:
  app: ldap
  template: ldap-buildconfig
message: |-
  For more information about using this template, see https://github.com/Worteks/wsweet-ci
metadata:
  annotations:
    description: OpenLDAP database - BuildConfig
      see https://github.com/Worteks/docker-ldap
    iconClass: icon-openshift
    openshift.io/display-name: OpenLDAP
    openshift.io/documentation-url: https://github.com/Worteks/wsweet-ci
    openshift.io/provider-display-name: Worteks
    openshift.io/support-url: https://www.worteks.com
    tags: openldap,ldap
  name: ldap-buildconfig
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Builds Wsweet OpenLDAP images
    labels:
      name: openldap-${FRONTNAME}-${LDAP_REPOSITORY_REF}
    name: openldap-${FRONTNAME}-${LDAP_REPOSITORY_REF}
  spec:
    failedBuildsHistoryLimit: 1
    resources:
      limits:
        cpu: 300m
        memory: 768Mi
    source:
      contextDir: /
      git:
        uri: ${LDAP_REPOSITORY_URL}
        ref: "${LDAP_REPOSITORY_REF}"
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        env:
        - name: DO_UPGRADE
          value: foo
        forcePull: false
    output:
      to:
        kind: ImageStreamTag
        name: openldap-${FRONTNAME}:${LDAP_REPOSITORY_REF}
    triggers:
    - type: ConfigChange
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
- name: LDAP_REPOSITORY_REF
  description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch
  displayName: Git Reference
  required: true
  value: master
- name: LDAP_REPOSITORY_URL
  description: The URL of the repository with your openldap Dockerfile
  displayName: Git Repository URL
  required: true
  value: https://github.com/Worteks/docker-ldap.git
