apiVersion: v1
kind: Template
labels:
  app: ldap
  template: ldap-imagestream
message: |-
  For more information about using this template, see https://github.com/Worteks/wsweet-ci
metadata:
  annotations:
    description: OpenLDAP database - ImageStream
      see https://github.com/Worteks/docker-ldap
    iconClass: icon-openshift
    openshift.io/display-name: OpenLDAP
    openshift.io/documentation-url: https://github.com/Worteks/wsweet-ci
    openshift.io/provider-display-name: Worteks
    openshift.io/support-url: https://www.worteks.com
    tags: openldap,ldap
  name: ldap-imagestream
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in Wsweet OpenLDAP image
    name: openldap-${FRONTNAME}
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
